import random

def execute(message=None):
    facts = [
        "The first computer virus, 'Brain,' was created in 1986 by two Pakistani brothers.",
        "Python was named after the British comedy series 'Monty Python's Flying Circus.'",
        "The first website ever created is still online at info.cern.ch.",
        "Google was originally called 'Backrub.'",
        "The first hard disk drive could hold only 5MB of data.",
        "The 'QWERTY' keyboard layout was designed in 1873 to slow down typing on mechanical typewriters.",
        "Email existed before the World Wide Web.",
        "The first webcam was used to monitor a coffee pot at the University of Cambridge.",
        "There are over 700 programming languages in the world.",
        "The first Apple logo featured Sir Isaac Newton sitting under an apple tree.",
        "The Apollo 11 computer had less processing power than today's smartphones.",
        "Bill Gates wrote his first computer program at age 13.",
        "The 'Ctrl+Alt+Del' command was created by IBM engineer David Bradley.",
        "The first domain name ever registered was 'symbolics.com' in 1985.",
        "The floppy disk was invented by IBM in 1967.",
        "CAPTCHA stands for 'Completely Automated Public Turing test to tell Computers and Humans Apart.'",
        "The first known programmer was Ada Lovelace, who worked on Charles Babbage's Analytical Engine.",
        "Steve Jobs was fired from Apple in 1985, the company he co-founded.",
        "The first computer game, 'Spacewar!,' was created in 1962.",
        "The term 'bug' in computing was inspired by an actual moth found in a computer in 1947.",
        "The '@' symbol was chosen for email addresses because it was rarely used in computing at the time.",
        "The first SMS message, sent in 1992, simply said 'Merry Christmas.'",
        "Over 90% of the world's currency exists only in digital form.",
        "Mark Zuckerberg created Facebook in his Harvard dorm room in 2004.",
        "The first version of Microsoft Windows was released in 1985.",
        "The Eiffel Tower has its own Twitter account.",
        "The first computer weighed over 27 tons and occupied 1,800 square feet.",
        "The first mobile phone call was made in 1973 by Martin Cooper.",
        "The 'thumbs up' emoji is the most-used emoji worldwide.",
        "HTML was invented by Tim Berners-Lee in 1991.",
        "The first computer mouse was made of wood.",
        "Linux was created by Linus Torvalds in 1991 as a hobby project.",
        "The average person spends over 6 hours a day using the internet.",
        "Amazon was originally an online bookstore.",
        "The first video ever uploaded to YouTube was titled 'Me at the zoo.'",
        "Twitter was originally called 'Twttr.'",
        "More than 3.5 billion Google searches are made every day.",
        "The longest word you can type using only your left hand on a QWERTY keyboard is 'stewardesses.'",
        "The Unicode standard has over 143,000 characters.",
        "The world's first 1TB hard drive was released in 2007.",
        "The term 'spam' for unwanted email comes from a Monty Python sketch.",
        "The concept of 'cloud computing' dates back to the 1960s.",
        "Over 500 hours of video are uploaded to YouTube every minute.",
        "The first smartphone, IBM Simon, was released in 1994.",
        "The average smartphone user checks their phone over 100 times a day.",
        "More than 2 billion websites exist on the internet today.",
        "Bluetooth is named after a 10th-century Scandinavian king, Harald 'Bluetooth' Gormsson.",
        "Over 90% of the world's data was created in the last two years.",
        "Typing 'Google in 1998' in Google search shows the website's original design.",
        "Cleopatras lived closer in time to the invention of the iPhone than to the building of the Great Pyramid of Giza.",
"group of owls is called a parliament.",
"There are more trees on Earth than stars in the Milky Way galaxy.",
"It snows metal on Venus.",
"There's a species of jellyfish that's biologically immortal.",
"A teaspoonful of neutron star would weigh 6 billion tons.",
"The population of Canada is smaller than the population of California.",
"Your nose and ears never stop growing.",
"Cleopatra lived closer to the invention of the iPhone than to the building of the Great Pyramid.",
"It's illegal to own just one guinea pig in Switzerland.",
"There are more possible iterations of a game of chess than there are atoms in the observable universe.",
"Bananas are slightly radioactive.",
"The sixth sick sheik's sixth sheep's sick is believed to be the toughest tongue twister in the English language.",
" The dot over the letter 'i' is called a tittle.",
" A single cloud can weigh more than a million pounds.",
"Astronauts can grow taller in space.",
" The surface area of a human lung is roughly the size of a tennis court.",
"It's physically impossible for pigs to look up into the sky.",
"The total length of blood vessels in the human body is about 60,000 miles.",
"A shrimp's heart is in its head.",
"There are more stars in the universe than grains of sand on all the beaches on Earth.",
"The world's oldest known tortoise lived to be 188 years old.",
" The coldest temperature ever recorded on Earth was -128.6°F (-89.2°C) in Antarctica.",
"The population of ants on Earth is estimated to be 10 quadrillion.",
"There are about 100,000 hairs on a human head.",
"The average person spends about six months of their life waiting for red lights to turn green.",
"Your brain is 80% water.",
"Koalas sleep up to 22 hours a day.",
"  The electric chair was invented by a dentist.",
" There are more chickens than people in the world.",
  "A giraffe can clean its ears with its 21-inch tongue.",
"  The heart of a shrimp is located in its head.",
 " The "Mona Lisa" has no eyebrows.",
"  It is illegal to drive a camel on a motorway in the UK.",
  "Polar bears are left-handed.",
"  Cleopatra lived closer to the invention of the iPhone than to the construction of the Great Pyramid of Giza.",
"  A cat can make over 100 different sounds, while a dog can only make about 10.",
"  The population of Canada is less than the population of California.",
"  The word "queue" is the only word in the English language that is spelled the same forwards and backwards. (Incorrect - this is false)",
"  A snail can sleep for three years.",
"It takes about 8 minutes for sunlight to reach the Earth.",
"  The sound of a lion's roar can be heard from up to 5 miles away.",
"  A Boeing 747's wingspan is longer than the Wright brothers' first flight.",
"  There are no clocks in the entire country of North Korea. (Partially true, but overstated)",
"  The total weight of all the ants on Earth is roughly equal to the total weight of all the humans on Earth.",
"  The human body contains enough iron to make a 3-inch nail.",
"  There is a species of fish that can survive out of water for up to four days.",
"  The Great Pyramid of Giza was once the tallest man-made structure in the world for over 3,800 years.",
"  The average person laughs about 15 times a day.",
"  A strawberry is not a berry, but a raspberry is.",
" The Eiffel Tower was originally meant to be temporary.",
"  The surface area of the Earth is about 197 million square miles.",
"  The human eye can distinguish between approximately 10 million different colors.",
"  A hippopotamus's sweat is pink.",
"  There are more trees on Earth than stars in the Milky Way.",
 " The lifespan of a housefly is about 28 days.",
"  A group of crows is called a murder.",
"The largest desert in the world is Antarctica.",
" A chameleon's eyes can move independently of each other.",
"  The longest recorded flight of a chicken is 13 seconds.",
"  The probability of being struck by lightning in your lifetime is about 1 in 15,300.",
" It is illegal to drive a car backwards on the Pennsylvania Turnpike.",
"  The first object to be launched into space was a German V-2 rocket.",
" There are more than 7,000 languages spoken in the world.",
"  The world's largest living organism is a fungus.",
"  The average person walks the equivalent of three times around the world in their lifetime.",
"  The human brain generates enough electricity to power a light bulb.",
"  A sneeze can travel at speeds of up to 100 mph.",
"  The sound of a dolphin's echolocation can be heard from up to 100 meters away.",
"  It is illegal to hunt camels in Arizona.",
"  The world's oldest known living tree is approximately 5,000 years old.",
" The letter J is the only letter that doesn't appear in the periodic table.",
"  A spider's silk is stronger than steel.",
"  The human heart beats about 100,000 times a day.",
" The average person spends about two years of their life brushing their teeth.",
"  There are about 206 bones in the human body.",
" The Great Wall of China is visible from space (This is a myth).",
"  The Earth's rotation is gradually slowing down.",
" The length of a human's small intestine is about 23 feet.",
"  The world's longest mountain range is underwater.",
"  A jellyfish is 95% water.",
" There are more than 100,000 different types of fungi.",
" The temperature of the sun's surface is approximately 10,000 degrees Fahrenheit.",
" The speed of light is approximately 186,000 miles per second.",
" It takes about 27 days for the moon to orbit the Earth.",
"  The Earth is about 4.54 billion years old.",
"The human body contains about 100 trillion cells.",
"The diameter of the Earth is approximately 7,918 miles.",
"The population of the world is currently over 8 billion people."
    ]
    return random.choice(facts)
